# Création d'image 
FROM mariadb:11.8.3

#Variables d'environnement

# Mot de passe ROOt du serveur de base de données
ENV MARIADB_ROOT_PASSWORD=azerty
# Nom de la base de données qui sera crée au 1er démararage du conteneur
ENV MARIADB_DATABASE=MYSQL_DATABASE
# Nom d'utilisateur pour se connecter à la base de données
ENV MARIADB_USER=ludo

ENV MARIADB_PASSWORD=1234
